# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "interprocess"
version = "2.0.0"
authors = ["Kotauskas <v.toncharov@gmail.com>"]
edition = "2021"
rust-version = "1.66"
resolver = "2"
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/interprocess"
repository = "https://github.com/kotauskas/interprocess"

description = "Interprocess communication toolkit"
categories = ["os", "os::unix-apis", "os::windows-apis", "asynchronous"]
keywords = ["ipc", "shared_memory", "pipe", "unix_domain_socket"]

exclude = [
    "/.github/",
    "/README.tpl",
    "/Cargo.lock",
    "/.gitignore",
    "interprocess.code-workspace",
]

[features]
default = []
tokio = ["dep:tokio", "futures-core", "futures-io"]
doc_cfg = []

[dependencies]
tokio = { version = "1.28.0", features = [
    "sync",
    "rt",
    "net",
    "time",
    "io-util",
], optional = true }
futures-core = { version = "0.3.28", optional = true }
futures-io = { version = "0.3.28", optional = true }
to_method = "1.1"
cfg-if = "1.0.0"

[build-dependencies]
rustc_version = "0.4"

[dev-dependencies]
tokio = { version = "1.23.0", features = [
    "rt-multi-thread",
    "io-util",
    "sync",
    "macros",
] }
futures = "0.3.28"
anyhow = "1.0.32"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = [
    "std",
    "winbase",
    "winerror",
    "processthreadsapi",
    "fileapi",
    "handleapi",
    "namedpipeapi",
] }

[target.'cfg(unix)'.dependencies]
libc = { version = "0.2.137", features = ["extra_traits"] }

[package.metadata.docs.rs]
features = ["doc_cfg", "tokio"]
